package com.rabitah.backend.storage;

import java.io.*;import java.nio.file.*;import java.util.UUID;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.web.multipart.MultipartFile;import software.amazon.awssdk.auth.credentials.*;import software.amazon.awssdk.core.ResponseBytes;import software.amazon.awssdk.core.sync.RequestBody;import software.amazon.awssdk.regions.Region;import software.amazon.awssdk.services.s3.S3Client;import software.amazon.awssdk.services.s3.model.*;

/** Uses S3-compatible object storage in production (Railway + R2/S3), with a local fallback for development. */
@Service public final class MediaStorage {
 private final String provider,bucket;private final Path localRoot;private final S3Client s3;
 public MediaStorage(@Value("${rabitah.storage.provider:local}")String provider,@Value("${rabitah.storage.local-root:./uploads}")String root,@Value("${rabitah.storage.s3.bucket:}")String bucket,@Value("${rabitah.storage.s3.region:auto}")String region,@Value("${rabitah.storage.s3.endpoint:}")String endpoint,@Value("${rabitah.storage.s3.access-key:}")String key,@Value("${rabitah.storage.s3.secret-key:}")String secret,@Value("${rabitah.storage.s3.path-style:false}")boolean pathStyle)throws IOException{this.provider=provider;this.bucket=bucket;this.localRoot=Paths.get(root).toAbsolutePath().normalize();Files.createDirectories(localRoot);if("s3".equalsIgnoreCase(provider)){var b=S3Client.builder().region(Region.of(region)).credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(key,secret)));if(!endpoint.isBlank())b.endpointOverride(java.net.URI.create(endpoint));if(pathStyle)b.forcePathStyle(true);this.s3=b.build();}else this.s3=null;}
 public String save(String folder,MultipartFile file)throws IOException{String key=folder+"/"+UUID.randomUUID()+"-"+safe(file.getOriginalFilename());if(s3!=null){s3.putObject(PutObjectRequest.builder().bucket(bucket).key(key).contentType(file.getContentType()).build(),RequestBody.fromInputStream(file.getInputStream(),file.getSize()));}else{Path target=localRoot.resolve(key).normalize();Files.createDirectories(target.getParent());file.transferTo(target);}return key;}
 public String saveBytes(String folder,String filename,byte[] bytes,String contentType)throws IOException{String key=folder+"/"+UUID.randomUUID()+"-"+safe(filename);if(s3!=null){s3.putObject(PutObjectRequest.builder().bucket(bucket).key(key).contentType(contentType).build(),RequestBody.fromBytes(bytes));}else{Path target=localRoot.resolve(key).normalize();Files.createDirectories(target.getParent());Files.write(target,bytes,StandardOpenOption.CREATE_NEW);}return key;}
 public byte[] read(String key)throws IOException{if(s3!=null){ResponseBytes<GetObjectResponse> item=s3.getObjectAsBytes(GetObjectRequest.builder().bucket(bucket).key(key).build());return item.asByteArray();}Path target=localRoot.resolve(key).normalize();if(!target.startsWith(localRoot)||!Files.exists(target))throw new FileNotFoundException();return Files.readAllBytes(target);}
 public void delete(String key)throws IOException{if(s3!=null){s3.deleteObject(DeleteObjectRequest.builder().bucket(bucket).key(key).build());return;}Path target=localRoot.resolve(key).normalize();if(!target.startsWith(localRoot))throw new IOException("Invalid storage key");Files.deleteIfExists(target);}
 private String safe(String name){return (name==null?"upload":name).replaceAll("[^a-zA-Z0-9._-]","_");}
}
